### ISSUE TITLE
Unwanted same-site recognition: should beacons be listed here too?

### ISSUE THREAD

**Issue by JoGSal** [w3cping/privacy-threat-model#24]
Do beacons stop monitoring data (the behaviour of the user, the IP of the computer, the time and lenght the beacon was viewed, the type of browser, and previously set cookie values) after taking any of the actions listed under "A user might expect that their two visits won’t be associated if they:"?

**Comment by jyasskin** [comment]
https://www.w3.org/TR/beacon/ and https://fetch.spec.whatwg.org/#request-keepalive-flag don't describe any sort of monitoring, so I'm not sure if you're referring to something else or have misunderstood those features.

The kept-alive request should probably be ended when a site's storage is cleared, but that's an implication of the threat model, and not something that we need to specifically call out here.

**Comment by JoGSal** [comment]
Thank you, got that info from a definition search at https://www.webopedia.com/TERM/W/Web_beacon.html

> The kept-alive request should probably be ended when a site's storage is cleared, but that's an implication of the threat model, and not something that we need to specifically call out here.

Clear
